# Generated by Django 6.0.4 on 2026-05-19 07:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', unique=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('mentor', 'Преподаватель'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', unique=True, verbose_name='Телефон')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('direction', models.CharField(choices=[('OOP', 'ООП'), ('Python', 'Python'), ('C++', 'C++'), ('SysProg', 'Системное программирование'), ('WebProg', 'Web-программирование'), ('JS', 'JavaScript'), ('Algorithms', 'Алгоритмы'), ('DataStructer', 'Структуры данных')], max_length=100, verbose_name='Направление (напр. Python)')),
                ('min_skill_level', models.IntegerField(default=1)),
                ('max_capacity', models.PositiveIntegerField(default=15)),
                ('course', models.IntegerField(default=1)),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_groups', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='learning_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='mentors/avatars/')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('work_history', models.TextField(blank=True, default='Не указано', verbose_name='Опыт работы')),
                ('education_place', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('qualifications', models.TextField(verbose_name='Квалификации/Сертификаты')),
                ('skills', models.CharField(blank=True, default='Не указано', max_length=255, verbose_name='Навыки (через запятую)')),
                ('video_presentation', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео-визитку')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен администрацией')),
                ('internal_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_students_taught', models.PositiveIntegerField(default=0)),
                ('experience_start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала работы в школе')),
                ('is_portfolio_public', models.BooleanField(default=False, verbose_name='Сделать портфолио публичным')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='Заморожен')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль Ментора',
                'verbose_name_plural': 'Профили Менторов',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_goal', models.TextField(blank=True, default='Не указано', help_text='Что хочет освоить?', verbose_name='Цель обучения')),
                ('current_education', models.CharField(max_length=255, verbose_name='Место текущего обучения')),
                ('is_portfolio_public', models.BooleanField(default=False, verbose_name='Сделать портфолио публичным')),
                ('portfolio_links', models.JSONField(blank=True, default=list, help_text='Список ссылок на проекты')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('attendance_rate', models.PositiveIntegerField(default=0)),
                ('potential_points', models.IntegerField(default=0, verbose_name='Очки потенциала')),
                ('total_speed_score', models.FloatField(default=0.0, verbose_name='Среднее кол-во попыток')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Коэффициент скорости решения')),
                ('total_recommendations', models.PositiveIntegerField(default=0)),
                ('parent_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт родителя')),
                ('is_parent_contact_approved', models.BooleanField(default=False)),
                ('is_frozen', models.BooleanField(default=False)),
                ('internal_admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки для администрации')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль Студента',
                'verbose_name_plural': 'Профили Студентов',
            },
        ),
    ]
