# Generated by Django 6.0.4 on 2026-04-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        ('users', '0002_alter_groups_mentor_alter_mentors_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(max_length=30, verbose_name='Название задания')),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField(help_text='Время сдачи задания')),
                ('description', models.TextField(max_length=635)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.groups', verbose_name='Группы')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exercises', to='users.mentors', verbose_name='Препод')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='plan.subjects', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='solutions/photos/%Y/%m/%d/')),
                ('document', models.FileField(blank=True, null=True, upload_to='solutions/docs/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tasks.exercises', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='users.student', verbose_name='Студент')),
            ],
        ),
    ]
