# Generated by Django 6.0.4 on 2026-04-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_groups_mentor_alter_mentors_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_name', models.CharField(max_length=35, verbose_name='Название предмета')),
                ('time_amount', models.PositiveIntegerField(default=72, help_text='Общее количество академических часов')),
                ('control_type', models.CharField(choices=[('EXAM', 'Экзамен'), ('CREDIT', 'Зачет'), ('PROJECT', 'Курсовая работа')], default='EXAM', max_length=20)),
                ('semestr', models.IntegerField(choices=[(1, '1 семестр'), (2, '2 семестр'), (3, '3 семестр'), (4, '4 семестр'), (5, '5 семестр'), (6, '6 семестр'), (7, '7 семестр'), (8, '8 семестр')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=1, max_length=20)),
                ('lesson_number', models.PositiveIntegerField()),
                ('classroom', models.CharField(max_length=10)),
                ('lesson_type', models.CharField(choices=[('LECTURE', 'Лекция'), ('PRACTICE', 'Практика'), ('LAB', 'Лабораторная')], default='LECTURE', max_length=15)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.groups')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mentors')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.subjects')),
            ],
        ),
    ]
